import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";

const inter_init = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "700", "500"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter_init.variable} antialiased font-poppins  bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
